# Generated by Django 4.2.4 on 2023-09-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdeviceinfo',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
