# Generated by Django 4.2.4 on 2023-09-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_alter_networkdeviceinfo_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.networkdeviceinfo')),
            ],
        ),
    ]
