# Generated by Django 4.1 on 2023-09-09 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_scriptinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptinfo',
            name='level',
            field=models.CharField(choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3')], default='L1', max_length=20),
        ),
        migrations.CreateModel(
            name='NetworkKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3')], default='L1', max_length=20)),
                ('script_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.scriptinfo')),
            ],
        ),
    ]
