# Generated by Django 4.1 on 2023-09-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_scriptinfo_level_networkkeyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptinfo',
            name='status',
        ),
        migrations.AlterField(
            model_name='scriptinfo',
            name='arguments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scriptinfo',
            name='execution_frequency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scriptinfo',
            name='script_file',
            field=models.FileField(blank=True, upload_to='scripts/'),
        ),
        migrations.AlterField(
            model_name='scriptinfo',
            name='version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
