# Generated by Django 4.1 on 2024-03-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scripts", "0008_scriptinfo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptinfo",
            name="domain",
            field=models.CharField(default="Network", max_length=255, unique=False),
            preserve_default=False,
        ),
    ]
