# Generated by Django 4.1 on 2024-03-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scripts", "0009_scriptinfo_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scriptinfo",
            name="domain",
            field=models.CharField(max_length=255),
        ),
    ]
